# Generated by Django 5.2.1 on 2025-05-24 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historico',
            name='valor',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='historico',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
