# Generated by Django 5.2.1 on 2025-05-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0002_historico_timestamp_historico_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
