# Generated by Django 5.2.1 on 2025-05-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0003_alter_historico_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='valor',
        ),
    ]
