# Generated by Django 5.2.1 on 2025-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0004_remove_sensor_timestamp_remove_sensor_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='mac_address',
            field=models.CharField(max_length=100),
        ),
    ]
